name: C Shell CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install make and gcc
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Compile the program
      - name: Compile the program
        run: make

      # Run the shell
      - name: Run the shell
        run: |
          echo "exit" | ./simple_shell
